// <auto-generated />
using System;
using EcclesiaCast.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcclesiaCast.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717155511_AddThemeTransparent")]
    partial class AddThemeTransparent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("EcclesiaCast.Core.Bible.BibleBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "Number")
                        .IsUnique();

                    b.ToTable("BibleBooks");
                });

            modelBuilder.Entity("EcclesiaCast.Core.Bible.BibleVerse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chapter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Verse")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "Chapter", "Verse");

                    b.ToTable("BibleVerses");
                });

            modelBuilder.Entity("EcclesiaCast.Core.Bible.BibleVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BibleVersions");
                });

            modelBuilder.Entity("EcclesiaCast.Core.Songs.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Copyright")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("EcclesiaCast.Core.Songs.SongSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StyleJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("SongSections");
                });

            modelBuilder.Entity("EcclesiaCast.Core.Themes.SlideTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlignH")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlignV")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("BackgroundDim")
                        .HasColumnType("REAL");

                    b.Property<string>("BackgroundImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Bold")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BoxHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("BoxWidth")
                        .HasColumnType("REAL");

                    b.Property<double?>("BoxX")
                        .HasColumnType("REAL");

                    b.Property<double?>("BoxY")
                        .HasColumnType("REAL");

                    b.Property<double>("CaptionFontSize")
                        .HasColumnType("REAL");

                    b.Property<int>("CaptionPosition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FitToWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Italic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MarginHorizontal")
                        .HasColumnType("REAL");

                    b.Property<double>("MarginVertical")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxFontSize")
                        .HasColumnType("REAL");

                    b.Property<double>("MinFontSize")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Shadow")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowCaption")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowVerseNumbers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowVersionName")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TransparentBackground")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Uppercase")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("EcclesiaCast.Data.Persistence.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("EcclesiaCast.Core.Bible.BibleBook", b =>
                {
                    b.HasOne("EcclesiaCast.Core.Bible.BibleVersion", null)
                        .WithMany("Books")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcclesiaCast.Core.Bible.BibleVerse", b =>
                {
                    b.HasOne("EcclesiaCast.Core.Bible.BibleBook", "Book")
                        .WithMany("Verses")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("EcclesiaCast.Core.Songs.SongSection", b =>
                {
                    b.HasOne("EcclesiaCast.Core.Songs.Song", null)
                        .WithMany("Sections")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcclesiaCast.Core.Bible.BibleBook", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("EcclesiaCast.Core.Bible.BibleVersion", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("EcclesiaCast.Core.Songs.Song", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
